/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 COfa.glb 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-80edec2de8c04a4fb335a48b550a2336
Title: Sofa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function COfa(props) {
  const { nodes, materials } = useGLTF('/public/COfa.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials['01___Default']} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/public/COfa.glb')
