/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tbag.glb 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/travel-bag-015a111073b548ceb7a2e0f7ec74db69
Title: Travel bag
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tbag(props) {
  const { nodes, materials } = useGLTF('/public/tbag.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.StingrayPBS1} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/public/tbag.glb')
